### ISSUE TITLE
use alt attributes on image tags

### ISSUE THREAD

**Issue by rimmesbe** [llopezcuervo/teacozy#2]
Try to get in the habit of describing your images with the alt attribute. This description will show up in case the image doesn't load, it is read by screen readers for accessibility purposes, and it makes your code look more professional.
https://www.codecademy.com/articles/accessibility

https://github.com/llopezcuervo/teacozy/blob/master/index.html#L41

**Comment by llopezcuervo** [comment]
Kind of been avoiding this out of laziness. It takes nothing to add and could mean a lot when the image doesn't load or for the visually impaired. Good reminder Ryan; thanks.

Leon
