### ISSUE TITLE
make reusable classes

### ISSUE THREAD

**Issue by rimmesbe** [llopezcuervo/teacozy#4]
This flex-container has too much styling in it to be a reusable class. Keep it simple and you can add more specific/unique styling directly to the element another way.
flex-container {
display: flex;
justify-content: center;
flex-wrap: wrap;
}
That is all you really need.

https://github.com/llopezcuervo/teacozy/blob/master/resources/css/style.css#L16-L24

**Comment by llopezcuervo** [comment]
Thanks for the tip!

Leon
