### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [llopezcuervo/teacozy#6]
Grade: Satisfactory

Summary: Nice job on this project, the site looks good. You used some good techniques and kept your code well organized. Take a look at the issues I created for some best practice tweaks as well as some new techniques you can start using. There are some official CSS naming conventions out there, I like the BEM method: http://getbem.com/introduction/
Overall nice job, you are ready for the next units.

**Comment by llopezcuervo** [comment]
Thank you very much Ryan for taking the time to provide constructive feedback on my project - much appreciated!
